name: dv-configbaker
description: |
  "This GitHub Action serves as a powerful tool to create a functional Dataverse instance, enabling developers to run tests and perform other critical tasks within their GitHub CI workflows."
inputs:
  create-dv:
    description: "Whether or not to create an example Dataverse"
    required: true
    default: "true"
runs:
  using: "composite"
  steps:
    - name: "Start Dataverse service in background"
      shell: bash
      run: |
        echo "::group::Start Dataverse service in background"
        docker compose \
        -f ${{ github.action_path }}/docker-compose.yml \
        -p apitest \
        --env-file ${{ github.action_path }}/.env.dataverse \
        up -d --quiet-pull && echo -e "✅ Dataverse containers have been started."
        echo "::endgroup::"
    # Bootstrap will wait up until accessible, so blocking here.
    - name: "Bootstrap Dataverse service"
      shell: bash
      run: |
        echo "::group::Bootstrap Dataverse service"
        docker run -i --network apitest_dataverse gdcc/configbaker:alpha bootstrap.sh dev
        echo "::endgroup::"
    - name: Retrieve API Token
      run: ${{ github.action_path }}/scripts/get_api_token.sh
      shell: bash
    - name: Create Dataverse
      run: ${{ github.action_path }}/scripts/create_dataverse.sh
      shell: bash

