on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test Dataverse Action
    env:
      PORT: 8080
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: Run Dataverse Action
        uses: ./
        with:
          postgresql_version: 15
          create-dv: true
      - name: Check Dataverse Setup
        run: |
          echo $(curl http://localhost:8080/api/info/version) && \
          echo $(curl http://localhost:8080/api/metadatablocks)