name: Test action
on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test Dataverse Action
    env:
      PORT: 8080
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: Run Dataverse Action
        id: dataverse
        uses: ./
        with:
          postgresql_version: 15
          jvm_options: |
            dataverse.api.signature-secret=eikaizieb2Oghaex
            dataverse.pid.datacite.rest-api-url=https://api.datacite.org
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest
      - name: Check Dataverse Setup
        env:
          API_TOKEN: ${{ steps.dataverse.outputs.api_token }}
          BASE_URL: ${{ steps.dataverse.outputs.base_url }}
        run: |
          python3 -m pytest .github/workflows/scripts/test_dataverse.py